using System;

namespace SDG.Unturned
{
	public enum ESteamRejection
	{
		SERVER_FULL,
		WRONG_HASH_LEVEL,
		WRONG_HASH_ASSEMBLY,
		WRONG_VERSION,
		WRONG_PASSWORD,
		NAME_PLAYER_SHORT,
		NAME_PLAYER_LONG,
		NAME_PLAYER_INVALID,
		NAME_PLAYER_NUMBER,
		NAME_CHARACTER_SHORT,
		NAME_CHARACTER_LONG,
		NAME_CHARACTER_INVALID,
		NAME_CHARACTER_NUMBER,
		PRO_SERVER,
		PRO_CHARACTER,
		PRO_DESYNC,
		PRO_APPEARANCE,
		ALREADY_PENDING,
		ALREADY_CONNECTED,
		NOT_PENDING,
		LATE_PENDING,
		WHITELISTED,
		AUTH_VERIFICATION,
		AUTH_NO_STEAM,
		AUTH_LICENSE_EXPIRED,
		AUTH_VAC_BAN,
		AUTH_ELSEWHERE,
		AUTH_TIMED_OUT,
		AUTH_USED,
		AUTH_NO_USER,
		AUTH_PUB_BAN,
		AUTH_ECON_DESERIALIZE,
		AUTH_ECON_VERIFY,
		PING,
		PLUGIN,
		CLIENT_MODULE_DESYNC,
		SERVER_MODULE_DESYNC
	}
}
